"""create phase 2 schema

Revision ID: af9f68503878
Revises: 
Create Date: 2026-08-20 08:47:58.635549
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'af9f68503878'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('employee_id', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'company_id'),
    sa.UniqueConstraint('employee_id', 'company_id', name='uq_employees_employee_company')
    )
    op.create_index('ix_employees_company_id', 'employees', ['company_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role in ('admin')", name='ck_users_role'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_company_id', 'users', ['company_id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('action_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('employee_id', sa.String(length=64), nullable=True),
    sa.Column('proposed_arguments', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("action_type in ('create_upgrade_order', 'open_remediation_ticket', 'flag_device_for_replacement', 'notify_employee')", name='ck_action_proposals_action_type'),
    sa.CheckConstraint("status in ('PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'EXECUTED', 'FAILED')", name='ck_action_proposals_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_action_proposals_company_id', 'action_proposals', ['company_id'], unique=False)
    op.create_index('ix_action_proposals_status', 'action_proposals', ['status'], unique=False)
    op.create_index('ix_action_proposals_user_id', 'action_proposals', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=True),
    sa.Column('resource_type', sa.String(length=128), nullable=True),
    sa.Column('resource_id', sa.String(length=128), nullable=True),
    sa.Column('arguments', sa.JSON(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_company_id', 'audit_logs', ['company_id'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_event_type', 'audit_logs', ['event_type'], unique=False)
    op.create_index('ix_audit_logs_session_id', 'audit_logs', ['session_id'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('devices',
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('employee_id', sa.String(length=64), nullable=True),
    sa.Column('serial_number', sa.String(length=128), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('model_identifier', sa.String(length=128), nullable=True),
    sa.Column('processor', sa.String(length=255), nullable=True),
    sa.Column('hardware_uuid', sa.String(length=128), nullable=True),
    sa.Column('total_memory_label', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['employee_id', 'company_id'], ['employees.employee_id', 'employees.company_id'], ),
    sa.PrimaryKeyConstraint('device_id', 'company_id'),
    sa.UniqueConstraint('device_id', 'company_id', name='uq_devices_device_company')
    )
    op.create_index('ix_devices_company_id', 'devices', ['company_id'], unique=False)
    op.create_index('ix_devices_employee_id', 'devices', ['employee_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('employee_id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status in ('QUEUED', 'SENT', 'FAILED', 'CANCELLED')", name='ck_notifications_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_company_id', 'notifications', ['company_id'], unique=False)
    op.create_index('ix_notifications_device_id', 'notifications', ['device_id'], unique=False)
    op.create_index('ix_notifications_employee_id', 'notifications', ['employee_id'], unique=False)
    op.create_table('remediation_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('check_id', sa.String(length=128), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status in ('OPEN', 'CLOSED', 'CANCELLED')", name='ck_remediation_tickets_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_remediation_tickets_check_id', 'remediation_tickets', ['check_id'], unique=False)
    op.create_index('ix_remediation_tickets_company_id', 'remediation_tickets', ['company_id'], unique=False)
    op.create_index('ix_remediation_tickets_device_id', 'remediation_tickets', ['device_id'], unique=False)
    op.create_table('replacement_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status in ('OPEN', 'CLOSED', 'CANCELLED')", name='ck_replacement_requests_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_replacement_requests_company_id', 'replacement_requests', ['company_id'], unique=False)
    op.create_index('ix_replacement_requests_device_id', 'replacement_requests', ['device_id'], unique=False)
    op.create_table('upgrade_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('component', sa.String(length=128), nullable=False),
    sa.Column('spec', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status in ('OPEN', 'CLOSED', 'CANCELLED')", name='ck_upgrade_orders_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_upgrade_orders_company_id', 'upgrade_orders', ['company_id'], unique=False)
    op.create_index('ix_upgrade_orders_device_id', 'upgrade_orders', ['device_id'], unique=False)
    op.create_table('telemetry_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('agent_version', sa.String(length=64), nullable=True),
    sa.Column('os_platform', sa.String(length=64), nullable=True),
    sa.Column('os_product_name', sa.String(length=128), nullable=True),
    sa.Column('os_product_version', sa.String(length=64), nullable=True),
    sa.Column('os_build_version', sa.String(length=64), nullable=True),
    sa.Column('os_architecture', sa.String(length=64), nullable=True),
    sa.Column('os_kernel_name', sa.String(length=64), nullable=True),
    sa.Column('os_kernel_release', sa.String(length=64), nullable=True),
    sa.Column('os_hostname', sa.String(length=255), nullable=True),
    sa.Column('ram_bytes', sa.Integer(), nullable=True),
    sa.Column('total_memory_bytes', sa.Integer(), nullable=True),
    sa.Column('used_memory_bytes', sa.Integer(), nullable=True),
    sa.Column('free_memory_bytes', sa.Integer(), nullable=True),
    sa.Column('page_size_bytes', sa.Integer(), nullable=True),
    sa.Column('battery_present', sa.Boolean(), nullable=True),
    sa.Column('battery_charging_status', sa.String(length=64), nullable=True),
    sa.Column('battery_percentage', sa.Integer(), nullable=True),
    sa.Column('battery_condition', sa.String(length=64), nullable=True),
    sa.Column('battery_cycle_count', sa.Integer(), nullable=True),
    sa.Column('battery_full_charge_capacity', sa.Integer(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['device_id', 'company_id'], ['devices.device_id', 'devices.company_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'collected_at', name='uq_telemetry_device_collected_at')
    )
    op.create_index('ix_telemetry_collected_at', 'telemetry_snapshots', ['collected_at'], unique=False)
    op.create_index('ix_telemetry_company_device_collected', 'telemetry_snapshots', ['company_id', 'device_id', 'collected_at'], unique=False)
    op.create_index('ix_telemetry_company_id', 'telemetry_snapshots', ['company_id'], unique=False)
    op.create_index('ix_telemetry_device_id', 'telemetry_snapshots', ['device_id'], unique=False)
    op.create_table('compliance_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('check_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['telemetry_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_compliance_results_check_id', 'compliance_results', ['check_id'], unique=False)
    op.create_index('ix_compliance_results_company_id', 'compliance_results', ['company_id'], unique=False)
    op.create_index('ix_compliance_results_device_id', 'compliance_results', ['device_id'], unique=False)
    op.create_index('ix_compliance_results_severity', 'compliance_results', ['severity'], unique=False)
    op.create_index('ix_compliance_results_snapshot_id', 'compliance_results', ['snapshot_id'], unique=False)
    op.create_index('ix_compliance_results_status', 'compliance_results', ['status'], unique=False)
    op.create_table('disk_volumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('volume_name', sa.String(length=255), nullable=True),
    sa.Column('file_system', sa.String(length=64), nullable=True),
    sa.Column('mount_point', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('available_bytes', sa.Integer(), nullable=True),
    sa.Column('encrypted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['telemetry_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_disk_volumes_company_id', 'disk_volumes', ['company_id'], unique=False)
    op.create_index('ix_disk_volumes_device_id', 'disk_volumes', ['device_id'], unique=False)
    op.create_index('ix_disk_volumes_snapshot_id', 'disk_volumes', ['snapshot_id'], unique=False)
    op.create_table('installed_software',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=128), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['telemetry_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_installed_software_company_id', 'installed_software', ['company_id'], unique=False)
    op.create_index('ix_installed_software_device_id', 'installed_software', ['device_id'], unique=False)
    op.create_index('ix_installed_software_name', 'installed_software', ['name'], unique=False)
    op.create_index('ix_installed_software_snapshot_id', 'installed_software', ['snapshot_id'], unique=False)
    op.create_table('network_interfaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('family', sa.String(length=64), nullable=True),
    sa.Column('interface_name', sa.String(length=128), nullable=True),
    sa.Column('internal', sa.Boolean(), nullable=True),
    sa.Column('mac', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['telemetry_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_network_interfaces_company_id', 'network_interfaces', ['company_id'], unique=False)
    op.create_index('ix_network_interfaces_device_id', 'network_interfaces', ['device_id'], unique=False)
    op.create_index('ix_network_interfaces_snapshot_id', 'network_interfaces', ['snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_network_interfaces_snapshot_id', table_name='network_interfaces')
    op.drop_index('ix_network_interfaces_device_id', table_name='network_interfaces')
    op.drop_index('ix_network_interfaces_company_id', table_name='network_interfaces')
    op.drop_table('network_interfaces')
    op.drop_index('ix_installed_software_snapshot_id', table_name='installed_software')
    op.drop_index('ix_installed_software_name', table_name='installed_software')
    op.drop_index('ix_installed_software_device_id', table_name='installed_software')
    op.drop_index('ix_installed_software_company_id', table_name='installed_software')
    op.drop_table('installed_software')
    op.drop_index('ix_disk_volumes_snapshot_id', table_name='disk_volumes')
    op.drop_index('ix_disk_volumes_device_id', table_name='disk_volumes')
    op.drop_index('ix_disk_volumes_company_id', table_name='disk_volumes')
    op.drop_table('disk_volumes')
    op.drop_index('ix_compliance_results_status', table_name='compliance_results')
    op.drop_index('ix_compliance_results_snapshot_id', table_name='compliance_results')
    op.drop_index('ix_compliance_results_severity', table_name='compliance_results')
    op.drop_index('ix_compliance_results_device_id', table_name='compliance_results')
    op.drop_index('ix_compliance_results_company_id', table_name='compliance_results')
    op.drop_index('ix_compliance_results_check_id', table_name='compliance_results')
    op.drop_table('compliance_results')
    op.drop_index('ix_telemetry_device_id', table_name='telemetry_snapshots')
    op.drop_index('ix_telemetry_company_id', table_name='telemetry_snapshots')
    op.drop_index('ix_telemetry_company_device_collected', table_name='telemetry_snapshots')
    op.drop_index('ix_telemetry_collected_at', table_name='telemetry_snapshots')
    op.drop_table('telemetry_snapshots')
    op.drop_index('ix_upgrade_orders_device_id', table_name='upgrade_orders')
    op.drop_index('ix_upgrade_orders_company_id', table_name='upgrade_orders')
    op.drop_table('upgrade_orders')
    op.drop_index('ix_replacement_requests_device_id', table_name='replacement_requests')
    op.drop_index('ix_replacement_requests_company_id', table_name='replacement_requests')
    op.drop_table('replacement_requests')
    op.drop_index('ix_remediation_tickets_device_id', table_name='remediation_tickets')
    op.drop_index('ix_remediation_tickets_company_id', table_name='remediation_tickets')
    op.drop_index('ix_remediation_tickets_check_id', table_name='remediation_tickets')
    op.drop_table('remediation_tickets')
    op.drop_index('ix_notifications_employee_id', table_name='notifications')
    op.drop_index('ix_notifications_device_id', table_name='notifications')
    op.drop_index('ix_notifications_company_id', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_devices_employee_id', table_name='devices')
    op.drop_index('ix_devices_company_id', table_name='devices')
    op.drop_table('devices')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_session_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_event_type', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_company_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_action_proposals_user_id', table_name='action_proposals')
    op.drop_index('ix_action_proposals_status', table_name='action_proposals')
    op.drop_index('ix_action_proposals_company_id', table_name='action_proposals')
    op.drop_table('action_proposals')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_company_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_employees_company_id', table_name='employees')
    op.drop_table('employees')
    op.drop_table('companies')
    # ### end Alembic commands ###
